# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

references:
  ## Cache

    cache_key: &cache_key
      key: cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
    restore_cache: &restore_cache
      restore_cache:
        <<: *cache_key
    save_cache: &save_cache
      save_cache:
        <<: *cache_key
        paths:
          - ~/.gradle
          - ~/.m2


    ## Keys

    # Android Key Store

    export_android_key: &export_android_key
      run:
        name: Export Android key store environment variable
        command: echo 'export ANDROID_KEY_STORE="$((123456)/mvpkotlin.jks)"' >> $BASH_ENV
    decode_android_key: &decode_android_key
      run:
        name: Decode Android key store
        command: echo $ANDROID_KEY_STORE | base64 -di > mvpkotlin.jks

jobs:
  build:
    docker:
        - image: circleci/android:api-25-alpha
    working_directory: ~/mvpKotlin

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
        - checkout
        - *restore_cache
        - run:
              name: chmod permissions
              command: chmod +x ./gradlew
        - run:
              name: Download dependencies
              command: ./gradlew androidDependencies
        - *save_cache
        - *export_android_key
        - *decode_android_key
        - *save_cache
        - run:
              name: Run Test
              command: ./gradlew lint test
        - store_test_results:
              path: app/build/test-results
              destination: test-results/
        - store_artifacts:
              path: app/build/test-results
              prefix: test-results/
        - run:
              name: Initial build
              command: ./gradlew clean assembleRelease --no-daemon --stacktrace
        - store_artifacts:
              path: app/build/outputs/apk/
              destination: apks/

  test:
    docker:
        - image: circleci/android:api-25-alpha
    steps:
        - checkout
        - run:
                name: Test
                command: ./gradlew lint test
        - store_test_results:
                path: app/build/test-results
        - store_artifacts:
                path: test-results.xml
                prefix: tests