# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
        - image: circleci/android:api-25-alpha
    working_directory: ~/mvpKotlin

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
        - checkout
        - restore_cache:
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
              name: chmod permissions
              command: chmod +x ./gradlew
        - run:
              name: Download Dependencies
              command: ./gradlew androidDependencies
        - save_cache:
              paths:
                    - ~/.gradle
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
              name: Run Tests
              command: ./gradlew lint test
        - store_artifacts:
              path: /app/build/outputs/apk
              destination: apks/
  test:
    docker:
        - image: circleci/android:api-25-alpha
    steps:
        - checkout
          - run:
            command: Test
        - store_artifacts:
                      path: test-results.xml
                      prefix: tests