# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
        - image: circleci/android:api-25-alpha

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/mvpKotlin

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
        - checkout
        - run:
              name: chmod permissions
              command: chmod +x ./gradlew
        - run:
              name: Download Dependencies
              command: ./gradlew androidDependencies
        - save_cache:
              paths:
                    - ~/.gradle
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
              name: Run Tests
              command: ./gradlew lint test
        - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
        - store_artifacts:
                path: /tmp/artifact-1
                        destination: artifact-file
        - store_artifacts:
                  path: /tmp/artifacts




