# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "lint test")
    increment_version_code(
              gradle_file_path: "app/build.gradle",

    )
  end

  desc "Submit a new Alpha Build to play Store"
  lane :alpha do
    new_version_code = increment_version_code(
       gradle_file_path: "app/build.gradle",

    )
    desc "Version CODE: ${new_version_code}"
    gradle(task: 'assemble', build_type: 'Release')
#    upload_to_play_store(track: 'alpha')
#    slack(message: 'Successfully distributed a new beta build')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
